create extension if not exists pgcrypto;
create table public.user_roles(user_id uuid references auth.users on delete cascade, role text not null check(role in('admin')), primary key(user_id,role));
create or replace function public.has_role(requested_role text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=requested_role); $$;
revoke all on function public.has_role(text) from public;
grant execute on function public.has_role(text) to authenticated;
create table public.brands(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,created_at timestamptz default now());
create table public.categories(id uuid primary key default gen_random_uuid(),brand_id uuid not null references public.brands on delete cascade,name text not null,slug text not null,unique(brand_id,slug));
create table public.subcategories(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.categories on delete cascade,name text not null,slug text not null,unique(category_id,slug));
create table public.products(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,description text default '',sku text,price numeric(12,2) check(price is null or price >= 0),show_price boolean not null default false,brand_id uuid references public.brands,categoria_id uuid references public.categories,subcategoria_id uuid references public.subcategories,active boolean not null default false,rare boolean default false,sought boolean default false,yupoo_album_url text unique,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products on delete cascade,url text not null,storage_path text,sort_order int default 0,is_cover boolean default false);
create table public.store_settings(id int primary key default 1 check(id=1),whatsapp text not null default '5511999999999',default_message text not null default 'Olá! Tenho interesse em uma peça da Nord Imports:');
create table public.import_jobs(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users,status text default 'queued',phase text default 'preparando',total int default 0,created int default 0,duplicates int default 0,failures int default 0,source_url text not null,created_at timestamptz default now());
insert into public.store_settings(id,whatsapp,default_message) values(1,'5511999999999','Olá! Tenho interesse em uma peça da Nord Imports:') on conflict(id) do nothing;
create index products_active_created_idx on public.products(active,created_at desc);
create index products_brand_idx on public.products(brand_id);
create index products_category_idx on public.products(categoria_id);
create index products_subcategory_idx on public.products(subcategoria_id);
create index product_images_product_idx on public.product_images(product_id,sort_order);
create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;
create trigger products_touch_updated_at before update on public.products for each row execute function public.touch_updated_at();
create or replace function public.validate_product_taxonomy() returns trigger language plpgsql set search_path=public as $$ begin if not exists(select 1 from public.categories c where c.id=new.categoria_id and c.brand_id=new.brand_id) then raise exception 'A categoria não pertence à marca selecionada'; end if; if not exists(select 1 from public.subcategories s where s.id=new.subcategoria_id and s.category_id=new.categoria_id) then raise exception 'A subcategoria não pertence à categoria selecionada'; end if; return new; end; $$;
create trigger products_validate_taxonomy before insert or update of brand_id,categoria_id,subcategoria_id on public.products for each row when(new.brand_id is not null and new.categoria_id is not null and new.subcategoria_id is not null) execute function public.validate_product_taxonomy();
alter table public.user_roles enable row level security;alter table public.brands enable row level security;alter table public.categories enable row level security;alter table public.subcategories enable row level security;alter table public.products enable row level security;alter table public.product_images enable row level security;alter table public.store_settings enable row level security;alter table public.import_jobs enable row level security;
create policy "public active products" on public.products for select using(active or public.has_role('admin'));create policy "public taxonomy" on public.brands for select using(true);create policy "public categories" on public.categories for select using(true);create policy "public subcategories" on public.subcategories for select using(true);create policy "public images" on public.product_images for select using(exists(select 1 from public.products p where p.id=product_id and (p.active or public.has_role('admin'))));create policy "public settings" on public.store_settings for select using(true);
create policy "admin products" on public.products for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin brands" on public.brands for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin categories" on public.categories for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin subcategories" on public.subcategories for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin images" on public.product_images for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin settings" on public.store_settings for all using(public.has_role('admin')) with check(public.has_role('admin'));create policy "admin imports" on public.import_jobs for all using(public.has_role('admin')) with check(public.has_role('admin'));
insert into storage.buckets(id,name,public) values('products','products',true) on conflict do nothing;create policy "product images public" on storage.objects for select using(bucket_id='products');create policy "admin product uploads" on storage.objects for all using(bucket_id='products' and public.has_role('admin')) with check(bucket_id='products' and public.has_role('admin'));

-- Estrutura inicial da curadoria. Tudo pode ser alterado depois pelo painel.
insert into public.brands(name,slug) values ('Jordan','jordan'),('Nike','nike'),('Adidas','adidas'),('New Balance','new-balance'),('Supreme','supreme'),('Stüssy','stussy'),('Yeezy','yeezy'),('Carhartt WIP','carhartt-wip'),('Trapstar','trapstar'),('Essentials','essentials') on conflict(slug) do nothing;
with seed(brand,category,slug) as (values ('Jordan','Tênis','tenis'),('Nike','Tênis','tenis'),('Adidas','Tênis','tenis'),('New Balance','Tênis','tenis'),('Supreme','Roupas','roupas'),('Stüssy','Roupas','roupas'),('Yeezy','Calçados','calcados'),('Carhartt WIP','Roupas','roupas'),('Trapstar','Roupas','roupas'),('Essentials','Roupas','roupas')) insert into public.categories(brand_id,name,slug) select b.id,s.category,s.slug from seed s join public.brands b on b.name=s.brand on conflict(brand_id,slug) do nothing;
with seed(brand,category,subcategory,slug) as (values ('Jordan','Tênis','Basquete','basquete'),('Nike','Tênis','Casual','casual'),('Adidas','Tênis','Skate','skate'),('New Balance','Tênis','Lifestyle','lifestyle'),('Supreme','Roupas','Moletons','moletons'),('Stüssy','Roupas','Camisetas','camisetas'),('Yeezy','Calçados','Slides','slides'),('Carhartt WIP','Roupas','Jaquetas','jaquetas'),('Trapstar','Roupas','Jaquetas','jaquetas'),('Essentials','Roupas','Moletons','moletons')) insert into public.subcategories(category_id,name,slug) select c.id,s.subcategory,s.slug from seed s join public.brands b on b.name=s.brand join public.categories c on c.brand_id=b.id and c.name=s.category on conflict(category_id,slug) do nothing;
with seed(name,slug,brand,category,subcategory,description,rare,sought) as (values
('Air Jordan 1 High University Blue','air-jordan-1-high-university-blue','Jordan','Tênis','Basquete','Um ícone que atravessa quadras e ruas. O University Blue revisita a história de Michael Jordan com a combinação de cores de sua origem na Carolina do Norte.',false,true),
('Nike Dunk Low Panda','dunk-low-panda','Nike','Tênis','Casual','Contraste absoluto e construção clássica. O Dunk Low Panda transformou a silhueta universitária dos anos 80 em um dos pares mais versáteis da cultura sneaker.',false,true),
('Adidas Campus 00s Core Black','campus-00s-core-black','Adidas','Tênis','Skate','Proporções robustas, camurça e energia Y2K. Uma releitura do Campus que virou referência nas ruas.',false,true),
('New Balance 9060 Rain Cloud','new-balance-9060-rain-cloud','New Balance','Tênis','Lifestyle','Tecnologia de corrida dos anos 2000 encontra linhas futuristas em uma silhueta feita para colecionadores.',true,true),
('Supreme Box Logo Hoodie','supreme-box-logo-hoodie','Supreme','Roupas','Moletons','Uma das peças mais reconhecidas do streetwear, com construção pesada e o emblemático Box Logo.',true,false),
('Stüssy World Tour Tee','stussy-world-tour-tee','Stüssy','Roupas','Camisetas','O gráfico que conectou cidades e cenas culturais desde os primeiros capítulos do streetwear moderno.',false,false),
('Yeezy Slide Onyx','yeezy-slide-onyx','Yeezy','Calçados','Slides','Forma minimalista, conforto e uma das assinaturas mais influentes do design contemporâneo de calçados.',true,false),
('Carhartt WIP Detroit Jacket','carhartt-detroit-jacket','Carhartt WIP','Roupas','Jaquetas','Workwear autêntico com corte urbano. Uma peça que melhora com o tempo e carrega décadas de história.',false,false),
('Trapstar Irongate Puffer','trapstar-irongate-puffer','Trapstar','Roupas','Jaquetas','A presença londrina da Trapstar em uma jaqueta de volume marcante e acabamento técnico.',true,false),
('Fear of God Essentials Hoodie','essentials-relaxed-hoodie','Essentials','Roupas','Moletons','Minimalismo californiano, volume preciso e conforto elevado para o uniforme diário.',false,false)
) insert into public.products(name,slug,description,brand_id,categoria_id,subcategoria_id,active,rare,sought) select s.name,s.slug,s.description,b.id,c.id,sc.id,true,s.rare,s.sought from seed s join public.brands b on b.name=s.brand join public.categories c on c.brand_id=b.id and c.name=s.category join public.subcategories sc on sc.category_id=c.id and sc.name=s.subcategory on conflict(slug) do nothing;
insert into public.product_images(product_id,url,sort_order,is_cover) select p.id,'/hero-nord.png',0,true from public.products p where not exists(select 1 from public.product_images pi where pi.product_id=p.id);
