export type Product = { id:string; slug:string; name:string; brand:string; category:string; subcategory:string; description:string; image:string; images:string[]; active:boolean; rare?:boolean; sought?:boolean; price?:number|null; showPrice?:boolean; createdAt:string };
const hero="/hero-nord.png";
export const products:Product[]=[
{id:"1",slug:"air-jordan-1-high-university-blue",name:"Air Jordan 1 High University Blue",brand:"Jordan",category:"Tênis",subcategory:"Basquete",description:"Um ícone que atravessa quadras e ruas. O University Blue revisita a história de Michael Jordan com couro premium e a combinação de cores que marcou sua origem na Carolina do Norte.",image:hero,images:[hero,hero,hero],active:true,sought:true,createdAt:"2026-08-29"},
{id:"2",slug:"dunk-low-panda",name:"Nike Dunk Low Panda",brand:"Nike",category:"Tênis",subcategory:"Casual",description:"Contraste absoluto e construção clássica. O Dunk Low Panda transformou a silhueta universitária dos anos 80 em um dos pares mais versáteis da cultura sneaker.",image:hero,images:[hero,hero],active:true,sought:true,createdAt:"2026-08-26"},
{id:"3",slug:"campus-00s-core-black",name:"Adidas Campus 00s Core Black",brand:"Adidas",category:"Tênis",subcategory:"Skate",description:"Proporções robustas, camurça e energia Y2K. Uma releitura do Campus que virou referência nas ruas.",image:hero,images:[hero,hero],active:true,sought:true,createdAt:"2026-08-21"},
{id:"4",slug:"new-balance-9060-rain-cloud",name:"New Balance 9060 Rain Cloud",brand:"New Balance",category:"Tênis",subcategory:"Lifestyle",description:"Tecnologia de corrida dos anos 2000 encontra linhas futuristas em uma silhueta feita para colecionadores.",image:hero,images:[hero,hero],active:true,sought:true,rare:true,createdAt:"2026-08-18"},
{id:"5",slug:"supreme-box-logo-hoodie",name:"Supreme Box Logo Hoodie",brand:"Supreme",category:"Roupas",subcategory:"Moletons",description:"Uma das peças mais reconhecidas do streetwear, com construção pesada e o emblemático Box Logo.",image:hero,images:[hero,hero],active:true,rare:true,createdAt:"2026-08-15"},
{id:"6",slug:"stussy-world-tour-tee",name:"Stüssy World Tour Tee",brand:"Stüssy",category:"Roupas",subcategory:"Camisetas",description:"O gráfico que conectou cidades e cenas culturais desde os primeiros capítulos do streetwear moderno.",image:hero,images:[hero],active:true,createdAt:"2026-08-11"},
{id:"7",slug:"yeezy-slide-onyx",name:"Yeezy Slide Onyx",brand:"Yeezy",category:"Calçados",subcategory:"Slides",description:"Forma minimalista, conforto e uma das assinaturas mais influentes do design contemporâneo de calçados.",image:hero,images:[hero],active:true,rare:true,createdAt:"2026-08-08"},
{id:"8",slug:"carhartt-detroit-jacket",name:"Carhartt WIP Detroit Jacket",brand:"Carhartt WIP",category:"Roupas",subcategory:"Jaquetas",description:"Workwear de presença com corte urbano. Uma peça que melhora com o tempo e carrega décadas de história.",image:hero,images:[hero],active:true,createdAt:"2026-08-03"},
{id:"9",slug:"trapstar-irongate-puffer",name:"Trapstar Irongate Puffer",brand:"Trapstar",category:"Roupas",subcategory:"Jaquetas",description:"A presença londrina da Trapstar em uma jaqueta de volume marcante e acabamento técnico.",image:hero,images:[hero],active:true,rare:true,createdAt:"2026-07-29"},
{id:"10",slug:"essentials-relaxed-hoodie",name:"Fear of God Essentials Hoodie",brand:"Essentials",category:"Roupas",subcategory:"Moletons",description:"Minimalismo californiano, volume preciso e conforto elevado para o uniforme diário.",image:hero,images:[hero],active:true,createdAt:"2026-07-25"}];
export const brands=[...new Set(products.map(p=>p.brand))]; export const categories=[...new Set(products.map(p=>p.category))];
export const settings={whatsapp:"5549999797544",message:"Olá! Tenho interesse em uma peça da Nord Imports:"};
